#!/usr/bin/env node

require('shelljs/global');
var util = require('./util');

var modules = util.modules(getModules());

set('-e');
mkdir('-p', util.MODULE_HOME);
rm('-rf', util.VIPER_MODULES);

modules.forEach(main);
function main(moduleDict) {
    var module = moduleDict.name;
    util.clone(module, moduleDict.hash);
    util.sync(util.remoteDir(module), util.localDir(module));
    util.updateConf(module, util.gitHEAD(module));
}

// helper
function getModules() {
    var modules = process.argv.slice(2);

    if (!modules.length) {
        modules = util.clear(conf());
    }

    return modules;
}
